---
repos:
  - repo: https://gitlab.com/smop/pre-commit-hooks
    rev: v1.0.0
    hooks:
      - id: check-gitlab-ci
  - repo: https://github.com/jazzband/pip-tools
    rev: 6.12.1
    hooks:
      - id: pip-compile
        args: [--no-emit-index-url, --no-emit-trusted-host]
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.6.0  # Use the sha / tag you want to point at
    hooks:
      - id: autopep8
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        language_version: python3
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        language_version: python3
        additional_dependencies:
          - flake8-pytest-style
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1  # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        additional_dependencies:
          - types-cachetools
          - types-pytz
          - types-python-dateutil
          - types-requests
          - types-retry
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        language_version: python3
        exclude: tests/
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.0
    hooks:
      - id: python-safety-dependencies-check
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.28.0
    hooks:
      - id: yamllint
  - repo: https://github.com/rubik/xenon.git
    rev: v0.9.0
    hooks:
      - id: xenon
        args: [-bB, -mB, -aA]
        exclude: '^(tests/|.*vkad_code|plarin_connect_mt/db/startup.py).*$'
