---
version: '3.7'

services:
  rabbit_mq:
    image: rabbitmq:3.10.7-management
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass
    volumes:
      - rabbit_data:/var/lib/rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
  web:
    build:
      context: .
    command: celery -A src.main.app worker -B -l info -Q common -E
    env_file: ./config/.env
    environment:
      PYTHONPATH: /code/
    volumes:
      - ./config:/config/
    depends_on:
      - rabbit_mq
volumes:
  rabbit_data:
    driver: local
